### ISSUE TITLE
Unit test vs. static analysis

### ISSUE THREAD

**Issue by katexochen** [datosh/gau#4]
What are the benefits of using unit tests for this task compared to static analysis/linting?

**Comment by datosh** [comment]
I see the following benefits using a unit test based approach:

1. There is no extra tooling / CLI to be installed. Therefore it is easier to contribute to a project or onboard a new developer using standard tools. 
2. Comparing this with [arch-go](https://github.com/fdaines/arch-go), the user is limited to the configuration syntax provided by the static analyzer. Having a unit test / code based approach allows us to provide the user with more powerful tools to do custom checks.
